//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldBankBookService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.Shared")]
    public partial class AuthenticationHeader : object
    {
        
        private string AccessTokenField;
        
        private string CompanyCodeField;
        
        private System.Nullable<System.Guid> CompanyIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.BankBookCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.CreateBankBook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookShortName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookBankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookGeneralLedgerAccount))]
    public partial class Command : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankBookCommand", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.CreateBankBook))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookShortName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookBankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.ChangeBankBookGeneralLedgerAccount))]
    public partial class BankBookCommand : TwinfieldBankBookService.Command
    {
        
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBankBook", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class CreateBankBook : TwinfieldBankBookService.BankBookCommand
    {
        
        private TwinfieldBankBookService.BankAccount BankAccountField;
        
        private string GeneralLedgerAccountField;
        
        private string NameField;
        
        private string ShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.BankAccount BankAccount
        {
            get
            {
                return this.BankAccountField;
            }
            set
            {
                this.BankAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralLedgerAccount
        {
            get
            {
                return this.GeneralLedgerAccountField;
            }
            set
            {
                this.GeneralLedgerAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookName", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class ChangeBankBookName : TwinfieldBankBookService.BankBookCommand
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookShortName", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class ChangeBankBookShortName : TwinfieldBankBookService.BankBookCommand
    {
        
        private string ShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookBankAccount", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class ChangeBankBookBankAccount : TwinfieldBankBookService.BankBookCommand
    {
        
        private TwinfieldBankBookService.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.BankAccount BankAccount
        {
            get
            {
                return this.BankAccountField;
            }
            set
            {
                this.BankAccountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeBankBookGeneralLedgerAccount", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class ChangeBankBookGeneralLedgerAccount : TwinfieldBankBookService.BankBookCommand
    {
        
        private string GeneralLedgerAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralLedgerAccount
        {
            get
            {
                return this.GeneralLedgerAccountField;
            }
            set
            {
                this.GeneralLedgerAccountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class BankAccount : object
    {
        
        private string BicField;
        
        private string CountryField;
        
        private string IbanField;
        
        private string NameField;
        
        private string NbicField;
        
        private string NumberField;
        
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Bic
        {
            get
            {
                return this.BicField;
            }
            set
            {
                this.BicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Iban
        {
            get
            {
                return this.IbanField;
            }
            set
            {
                this.IbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nbic
        {
            get
            {
                return this.NbicField;
            }
            set
            {
                this.NbicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public partial class SecurityFault : object
    {
        
        private TwinfieldBankBookService.SecurityFaultCode CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.SecurityFaultCode Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public enum SecurityFaultCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderIsMissing = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonInvalid = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDeleted = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDisabled = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationInactive = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSendFailed = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCluster = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectCompanyFailed = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLogonServer = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientInvalid = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameUserIsAlreadyLoggedIn = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOffByTwinfield = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidZlibData = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXmlData = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenUserCodeMissing = 351,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationCodeMissing = 352,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationIdMissing = 353,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenInvalid = 354,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenValidationUnavailable = 358,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyRequired = 359,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TokenAndSessionExist = 360,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyIdAndCodeExist = 361,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyNotSupported = 362,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayFormatNotSupported = 383,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayTypeNotSupported = 384,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public partial class ValidationFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankBookServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class BankBookServiceFault : object
    {
        
        private TwinfieldBankBookService.BankBookServiceFaultCode CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.BankBookServiceFaultCode Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankBookServiceFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public enum BankBookServiceFaultCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookNotFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookAlreadyExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookInvalidAccountSettings = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookInvalidGeneralLedgerAccount = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookAccountNumberMayNotBeChanged = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankBookGeneralLedgerAccountMayNotBeChanged = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.GetBankBook))]
    public partial class Query : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBankBook", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class GetBankBook : TwinfieldBankBookService.Query
    {
        
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldBankBookService.GetBankBookResult))]
    public partial class QueryResult : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBankBookResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class GetBankBookResult : TwinfieldBankBookService.QueryResult
    {
        
        private TwinfieldBankBookService.AutomaticBankProcessing AutomaticBankProcessingField;
        
        private TwinfieldBankBookService.BankAccount BankAccountField;
        
        private string GeneralLedgerAccountField;
        
        private string NameField;
        
        private string ShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.AutomaticBankProcessing AutomaticBankProcessing
        {
            get
            {
                return this.AutomaticBankProcessingField;
            }
            set
            {
                this.AutomaticBankProcessingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.BankAccount BankAccount
        {
            get
            {
                return this.BankAccountField;
            }
            set
            {
                this.BankAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralLedgerAccount
        {
            get
            {
                return this.GeneralLedgerAccountField;
            }
            set
            {
                this.GeneralLedgerAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomaticBankProcessing", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public partial class AutomaticBankProcessing : object
    {
        
        private bool ProcessDirectDebitsField;
        
        private bool ProcessPaymentsField;
        
        private bool ProcessStatementsField;
        
        private TwinfieldBankBookService.AutomaticBankProcessingSignUpState SignUpStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessDirectDebits
        {
            get
            {
                return this.ProcessDirectDebitsField;
            }
            set
            {
                this.ProcessDirectDebitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessPayments
        {
            get
            {
                return this.ProcessPaymentsField;
            }
            set
            {
                this.ProcessPaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcessStatements
        {
            get
            {
                return this.ProcessStatementsField;
            }
            set
            {
                this.ProcessStatementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldBankBookService.AutomaticBankProcessingSignUpState SignUpState
        {
            get
            {
                return this.SignUpStateField;
            }
            set
            {
                this.SignUpStateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomaticBankProcessingSignUpState", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
    public enum AutomaticBankProcessingSignUpState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldBankBookService.BankBookService")]
    public interface BankBookService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Process", ReplyAction="http://www.twinfield.com/BankBookService/ProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldBankBookService.SecurityFault), Action="http://www.twinfield.com/BankBookService/ProcessSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldBankBookService.ValidationFault), Action="http://www.twinfield.com/BankBookService/ProcessValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldBankBookService.BankBookServiceFault), Action="http://www.twinfield.com/BankBookService/ProcessBankBookServiceFaultFault", Name="BankBookServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
        TwinfieldBankBookService.ProcessResponse Process(TwinfieldBankBookService.CommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Process", ReplyAction="http://www.twinfield.com/BankBookService/ProcessResponse")]
        System.Threading.Tasks.Task<TwinfieldBankBookService.ProcessResponse> ProcessAsync(TwinfieldBankBookService.CommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Query", ReplyAction="http://www.twinfield.com/BankBookService/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldBankBookService.SecurityFault), Action="http://www.twinfield.com/BankBookService/QuerySecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldBankBookService.ValidationFault), Action="http://www.twinfield.com/BankBookService/QueryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldBankBookService.BankBookServiceFault), Action="http://www.twinfield.com/BankBookService/QueryBankBookServiceFaultFault", Name="BankBookServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankBookService")]
        TwinfieldBankBookService.QueryResponse Query(TwinfieldBankBookService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankBookService/Query", ReplyAction="http://www.twinfield.com/BankBookService/QueryResponse")]
        System.Threading.Tasks.Task<TwinfieldBankBookService.QueryResponse> QueryAsync(TwinfieldBankBookService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldBankBookService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldBankBookService.Command Command;
        
        public CommandRequest()
        {
        }
        
        public CommandRequest(TwinfieldBankBookService.AuthenticationHeader Authentication, string SessionId, TwinfieldBankBookService.Command Command)
        {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Command = Command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse
    {
        
        public ProcessResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldBankBookService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldBankBookService.Query Query;
        
        public QueryRequest()
        {
        }
        
        public QueryRequest(TwinfieldBankBookService.AuthenticationHeader Authentication, string SessionId, TwinfieldBankBookService.Query Query)
        {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldBankBookService.QueryResult Result;
        
        public QueryResponse()
        {
        }
        
        public QueryResponse(TwinfieldBankBookService.QueryResult Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface BankBookServiceChannel : TwinfieldBankBookService.BankBookService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BankBookServiceClient : System.ServiceModel.ClientBase<TwinfieldBankBookService.BankBookService>, TwinfieldBankBookService.BankBookService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BankBookServiceClient() : 
                base(BankBookServiceClient.GetDefaultBinding(), BankBookServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_BankBookService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankBookServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BankBookServiceClient.GetBindingForEndpoint(endpointConfiguration), BankBookServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankBookServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BankBookServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankBookServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BankBookServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TwinfieldBankBookService.ProcessResponse Process(TwinfieldBankBookService.CommandRequest request)
        {
            return base.Channel.Process(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldBankBookService.ProcessResponse> ProcessAsync(TwinfieldBankBookService.CommandRequest request)
        {
            return base.Channel.ProcessAsync(request);
        }
        
        public TwinfieldBankBookService.QueryResponse Query(TwinfieldBankBookService.QueryRequest request)
        {
            return base.Channel.Query(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldBankBookService.QueryResponse> QueryAsync(TwinfieldBankBookService.QueryRequest request)
        {
            return base.Channel.QueryAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_BankBookService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_BankBookService))
            {
                return new System.ServiceModel.EndpointAddress("https://api.accounting.twinfield.com/webservices/BankBookService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BankBookServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_BankBookService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BankBookServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_BankBookService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_BankBookService,
        }
    }
}
